### ISSUE TITLE
.

### ISSUE THREAD

**Issue by xFru1T** [shamhi/HamsterKombatBot#1575]
Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\79605\Downloads\HamsterKombatBot-main\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\79605\Downloads\HamsterKombatBot-main\HamsterKombatBot-main\bot\utils\__init__.py", line 4, in <module>
    from . import launcher
  File "C:\Users\79605\Downloads\HamsterKombatBot-main\HamsterKombatBot-main\bot\utils\launcher.py", line 7, in <module>
    from bot.config import settings
  File "C:\Users\79605\Downloads\HamsterKombatBot-main\HamsterKombatBot-main\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\79605\Downloads\HamsterKombatBot-main\HamsterKombatBot-main\bot\config\config.py", line 32, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Users\79605\Downloads\HamsterKombatBot-main\HamsterKombatBot-main\venv\Lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\Users\79605\Downloads\HamsterKombatBot-main\HamsterKombatBot-main\venv\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
RANDOM_TAPS_COUNT
  Input should be a valid list [type=list_type, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type
Press any key to continue . . .

**Comment by Stelfelics** [comment]
try to delete all files from the folder (except the session folder) and install the bot again. I just had the same problem and a complete reinstallation of the bot helped me.

**Comment by xFru1T** [comment]
> try to delete all files from the folder (except the session folder) and install the bot again. I just had the same problem and a complete reinstallation of the bot helped me.

Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\79605\Downloads\HamsterKombatBot-main (1)\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\79605\Downloads\HamsterKombatBot-main (1)\HamsterKombatBot-main\bot\utils\__init__.py", line 4, in <module>
    from . import launcher
  File "C:\Users\79605\Downloads\HamsterKombatBot-main (1)\HamsterKombatBot-main\bot\utils\launcher.py", line 7, in <module>
    from bot.config import settings
  File "C:\Users\79605\Downloads\HamsterKombatBot-main (1)\HamsterKombatBot-main\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\79605\Downloads\HamsterKombatBot-main (1)\HamsterKombatBot-main\bot\config\config.py", line 32, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Users\79605\Downloads\HamsterKombatBot-main (1)\HamsterKombatBot-main\venv\Lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\Users\79605\Downloads\HamsterKombatBot-main (1)\HamsterKombatBot-main\venv\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
API_ID
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
API_HASH
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
Press any key to continue . . .
