### ISSUE TITLE
[Error] Settings SLEEP_BY_MIN_ENERGY. The code stopped working after the last update

### ISSUE THREAD

**Issue by tt88952** [shamhi/HamsterKombatBot#171]
Traceback (most recent call last):
  File "/home/q/Desktop/bot/hamster/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/home/q/Desktop/bot/hamster/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/home/q/Desktop/bot/hamster/bot/utils/launcher.py", line 10, in <module>
    from bot.config import settings
  File "/home/q/Desktop/bot/hamster/bot/config/__init__.py", line 1, in <module>
    from .config import settings
  File "/home/q/Desktop/bot/hamster/bot/config/config.py", line 30, in <module>
    settings = Settings()
  File "/home/q/Desktop/bot/hamster/venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 84, in __init__
    super().__init__(
  File "/home/q/Desktop/bot/hamster/venv/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
SLEEP_BY_MIN_ENERGY
  Input should be a valid list [type=list_type, input_value=200, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type

**Comment by argentezzy** [comment]
in the .env file: 
**SLEEP_BY_MIN_ENERGY=[500,900]**

**Comment by XPacL** [comment]
SLEEP_BY_MIN_ENERGY=[n1,n2] - правильное значение установи в .env

**Comment by ButCheR-PRO** [comment]
Да, теперь нужно указывать два значения:
`SLEEP_BY_MIN_ENERGY=[1800,2400]`
