### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by disasdter** [shamhi/HamsterKombatBot#173]
Что-то я скорее всего сделал не так, не подскажите ?
Ошибка:

Select an action:

    1. Create session
    2. Run clicker

> 2
Traceback (most recent call last):
  File "C:\Users\disas\Desktop\HamsterKombatBot-main\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\disas\Desktop\HamsterKombatBot-main\main.py", line 8, in main
    await process()
  File "C:\Users\disas\Desktop\HamsterKombatBot-main\bot\utils\launcher.py", line 91, in process
    tg_clients = await get_tg_clients()
  File "C:\Users\disas\Desktop\HamsterKombatBot-main\bot\utils\launcher.py", line 50, in get_tg_clients
    raise FileNotFoundError("Not found session files")
FileNotFoundError: Not found session files

**Comment by si4man** [comment]
у тебя в папке сессий нет по всей видимости
