### ISSUE TITLE
Не запускается, ошибка pydantic

### ISSUE THREAD

**Issue by Playys228** [shamhi/HamsterKombatBot#1733]
(venv) root@germspTest:/home/playys/HamsterKombatBot# bash /home/playys/HamsterKombatBot/start.bash
/home/playys/HamsterKombatBot
Traceback (most recent call last):
  File "/home/playys/HamsterKombatBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/home/playys/HamsterKombatBot/bot/utils/__init__.py", line 4, in <module>
    from . import launcher
  File "/home/playys/HamsterKombatBot/bot/utils/launcher.py", line 7, in <module>
    from bot.config import settings
  File "/home/playys/HamsterKombatBot/bot/config/__init__.py", line 1, in <module>
    from .config import settings
  File "/home/playys/HamsterKombatBot/bot/config/config.py", line 34, in <module>
    settings = Settings()
  File "/home/playys/HamsterKombatBot/venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 140, in __init__
    super().__init__(
  File "/home/playys/HamsterKombatBot/venv/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
add_taps_on_turbo
  Extra inputs are not permitted [type=extra_forbidden, input_value='2500', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
apply_daily_turbo
  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden

**Comment by Openyoueyes** [comment]
same

**Comment by EugeneMartein** [comment]
Не правильные значения параметров в конфиге **add_taps_on_turbo** и **apply_daily_turbo**
