### ISSUE TITLE
Input should be a valid list [type=list_type, input_value=200, input_type=int]

### ISSUE THREAD

**Issue by igore4ick002** [shamhi/HamsterKombatBot#207]
Traceback (most recent call last):
  File "/root/home/HamsterKombatBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/home/HamsterKombatBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/home/HamsterKombatBot/bot/utils/launcher.py", line 10, in <module>
    from bot.config import settings
  File "/root/home/HamsterKombatBot/bot/config/__init__.py", line 1, in <module>
    from .config import settings
  File "/root/home/HamsterKombatBot/bot/config/config.py", line 30, in <module>
    settings = Settings()
  File "/root/home/HamsterKombatBot/venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 84, in __init__
    super().__init__(
  File "/root/home/HamsterKombatBot/venv/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
SLEEP_BY_MIN_ENERGY
  Input should be a valid list [type=list_type, input_value=200, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type

**Comment by ButCheR-PRO** [comment]
Dupe https://github.com/shamhi/HamsterKombatBot/issues/194 
Dupe 2 https://github.com/shamhi/HamsterKombatBot/issues/171
Dupe 3 https://github.com/shamhi/HamsterKombatBot/issues/162
