### ISSUE TITLE
После обновления репозитория выдаёт ошибку при запуске main.py

### ISSUE THREAD

**Issue by Typ3DHard** [shamhi/HamsterKombatBot#2094]
Доброго времени суток. Решил впервые за долгое время обновить репозиторий на фоне нововведений в Хомячке. После git pull в директории после запуска main.py получаю такое. (Работаю через Termux, но думаю, что это мало на что влияет)

```
Traceback (most recent call last):                                                        File "/data/data/com.termux/files/home/bot/HamsterKombatBot/main.py", line 4, in <module>                                                                                         from bot.utils.launcher import process
  File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/utils/__init__.py", line 2, in <module>                                                                           from . import launcher                                                                File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/utils/launcher.py", line 10, in <module>                                                                          from bot.config import settings                                                       File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/config/__init__.py", line 1, in <module>                                                                          from .config import settings                                                          File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/config/config.py", line 30, in <module>                                                                           settings = Settings()                                                                              ^^^^^^^^^^                                                                 File "/data/data/com.termux/files/home/bot/HamsterKombatBot/venv/lib/python3.11/site-packages/pydantic_settings/main.py", line 84, in __init__                                    super().__init__(                                                                     File "/data/data/com.termux/files/home/bot/HamsterKombatBot/venv/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__                                            self.__pydantic_validator__.validate_python(data, self_instance=self)               pydantic_core._pydantic_core.ValidationError: 7 validation errors for Settings          max_price                                                                                 Extra inputs are not permitted [type=extra_forbidden, input_value='100000000', input_type=str]                                                                                    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     max_combo_price                                                                           Extra inputs are not permitted [type=extra_forbidden, input_value='10000000', input_type=str]                                                                                     For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_taps                                                                                  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_delay_in_run                                                                   Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     random_delay_in_run                                                                       Extra inputs are not permitted [type=extra_forbidden, input_value='[0,15]', input_type=str]                                                                                       For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_mini_game_key                                                                  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_useragent                                                                      Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
```

**Comment by WeendVidente777** [comment]
пока все нормальные люди, кто шарит, спят я могу посоветовать проверить параметр use_random_useragent скорее всего в конфиге. Убедись что там правильное значение. А если не поможет, то подожди утра, когда нормальные люди проснутся.

**Comment by shamhi** [comment]
> Доброго времени суток. Решил впервые за долгое время обновить репозиторий на фоне нововведений в Хомячке. После git pull в директории после запуска main.py получаю такое. (Работаю через Termux, но думаю, что это мало на что влияет)
> 
> ```
> Traceback (most recent call last):                                                        File "/data/data/com.termux/files/home/bot/HamsterKombatBot/main.py", line 4, in <module>                                                                                         from bot.utils.launcher import process
>   File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/utils/__init__.py", line 2, in <module>                                                                           from . import launcher                                                                File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/utils/launcher.py", line 10, in <module>                                                                          from bot.config import settings                                                       File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/config/__init__.py", line 1, in <module>                                                                          from .config import settings                                                          File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/config/config.py", line 30, in <module>                                                                           settings = Settings()                                                                              ^^^^^^^^^^                                                                 File "/data/data/com.termux/files/home/bot/HamsterKombatBot/venv/lib/python3.11/site-packages/pydantic_settings/main.py", line 84, in __init__                                    super().__init__(                                                                     File "/data/data/com.termux/files/home/bot/HamsterKombatBot/venv/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__                                            self.__pydantic_validator__.validate_python(data, self_instance=self)               pydantic_core._pydantic_core.ValidationError: 7 validation errors for Settings          max_price                                                                                 Extra inputs are not permitted [type=extra_forbidden, input_value='100000000', input_type=str]                                                                                    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     max_combo_price                                                                           Extra inputs are not permitted [type=extra_forbidden, input_value='10000000', input_type=str]                                                                                     For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_taps                                                                                  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_delay_in_run                                                                   Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     random_delay_in_run                                                                       Extra inputs are not permitted [type=extra_forbidden, input_value='[0,15]', input_type=str]                                                                                       For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_mini_game_key                                                                  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_useragent                                                                      Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
> ```

Без кавычек '

**Comment by Typ3DHard** [comment]
> > Доброго времени суток. Решил впервые за долгое время обновить репозиторий на фоне нововведений в Хомячке. После git pull в директории после запуска main.py получаю такое. (Работаю через Termux, но думаю, что это мало на что влияет)
> > 
> > ```
> > Traceback (most recent call last):                                                        File "/data/data/com.termux/files/home/bot/HamsterKombatBot/main.py", line 4, in <module>                                                                                         from bot.utils.launcher import process
> >   File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/utils/__init__.py", line 2, in <module>                                                                           from . import launcher                                                                File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/utils/launcher.py", line 10, in <module>                                                                          from bot.config import settings                                                       File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/config/__init__.py", line 1, in <module>                                                                          from .config import settings                                                          File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/config/config.py", line 30, in <module>                                                                           settings = Settings()                                                                              ^^^^^^^^^^                                                                 File "/data/data/com.termux/files/home/bot/HamsterKombatBot/venv/lib/python3.11/site-packages/pydantic_settings/main.py", line 84, in __init__                                    super().__init__(                                                                     File "/data/data/com.termux/files/home/bot/HamsterKombatBot/venv/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__                                            self.__pydantic_validator__.validate_python(data, self_instance=self)               pydantic_core._pydantic_core.ValidationError: 7 validation errors for Settings          max_price                                                                                 Extra inputs are not permitted [type=extra_forbidden, input_value='100000000', input_type=str]                                                                                    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     max_combo_price                                                                           Extra inputs are not permitted [type=extra_forbidden, input_value='10000000', input_type=str]                                                                                     For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_taps                                                                                  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_delay_in_run                                                                   Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     random_delay_in_run                                                                       Extra inputs are not permitted [type=extra_forbidden, input_value='[0,15]', input_type=str]                                                                                       For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_mini_game_key                                                                  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_useragent                                                                      Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
> > ```
> 
> Без кавычек '

Код без кавычек

Traceback (most recent call last):                                                        File "/data/data/com.termux/files/home/bot/HamsterKombatBot/main.py", line 4, in <module>                                                                                         from bot.utils.launcher import process
  File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/utils/__init__.py", line 2, in <module>                                                                           from . import launcher                                                                File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/utils/launcher.py", line 10, in <module>                                                                          from bot.config import settings                                                       File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/config/__init__.py", line 1, in <module>                                                                          from .config import settings                                                          File "/data/data/com.termux/files/home/bot/HamsterKombatBot/bot/config/config.py", line 30, in <module>                                                                           settings = Settings()                                                                              ^^^^^^^^^^                                                                 File "/data/data/com.termux/files/home/bot/HamsterKombatBot/venv/lib/python3.11/site-packages/pydantic_settings/main.py", line 84, in __init__                                    super().__init__(                                                                     File "/data/data/com.termux/files/home/bot/HamsterKombatBot/venv/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__                                            self.__pydantic_validator__.validate_python(data, self_instance=self)               pydantic_core._pydantic_core.ValidationError: 7 validation errors for Settings          max_price                                                                                 Extra inputs are not permitted [type=extra_forbidden, input_value='100000000', input_type=str]                                                                                    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     max_combo_price                                                                           Extra inputs are not permitted [type=extra_forbidden, input_value='10000000', input_type=str]                                                                                     For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_taps                                                                                  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_delay_in_run                                                                   Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     random_delay_in_run                                                                       Extra inputs are not permitted [type=extra_forbidden, input_value='[0,15]', input_type=str]                                                                                       For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_mini_game_key                                                                  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden     use_random_useragent                                                                      Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]                                                                                         For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden

**Comment by Typ3DHard** [comment]
> пока все нормальные люди, кто шарит, спят я могу посоветовать проверить параметр use_random_useragent скорее всего в конфиге. Убедись что там правильное значение. А если не поможет, то подожди утра, когда нормальные люди проснутся. 

Неа, попробовал - не работает

**Comment by zxcuseme** [comment]
Исправил ошибку?

**Comment by Typ3DHard** [comment]
> Исправил ошибку? 

Нет ещё

**Comment by zxcuseme** [comment]
Удали бота, удали питон, и заново все установи, мне помогло
