### ISSUE TITLE
Error Traceback (most recent call last):   File "C:\Users\User\Desktop\1\HamsterKombatBot-main\main.py", line 4, in <module>     from bot.utils.launcher import process   File "C:\Users\User\Desktop\1\HamsterKombatBot-main\bot\utils\__init__.py", line 13, in <module>     if not os.path.exists(path='sessions'):            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: nt._path_exists() takes no keyword arguments

### ISSUE THREAD

**Issue by vanya12312e** [shamhi/HamsterKombatBot#2096]
При запуске main.py имею ошибку: 

Traceback (most recent call last):
  File "C:\Users\User\Desktop\1\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\User\Desktop\1\HamsterKombatBot-main\bot\utils\__init__.py", line 13, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments

**Comment by UMember** [comment]
install bat / sh заново запусти или по инструкции установки

**Comment by Akram14372562** [comment]
Did this solved?? I'm also facing this issue

**Comment by UbeySofta** [comment]
Same issue, tried with install.bat and manually
`C:\Users\Ubeysoft>cd /d c:\lib\bots\HamsterKombatBot\

c:\Lib\Bots\HamsterKombatBot>python -m venv venv

c:\Lib\Bots\HamsterKombatBot>venv\Scripts\activate

(venv) c:\Lib\Bots\HamsterKombatBot>pip install -r requirements.txt
Requirement already satisfied: aiohttp==3.9.5 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 1)) (3.9.5)
Requirement already satisfied: aiohttp-proxy==0.1.2 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 2)) (0.1.2)     
Requirement already satisfied: aiosignal==1.3.1 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: annotated-types==0.7.0 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 4)) (0.7.0)   
Requirement already satisfied: async-timeout==4.0.3 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 5)) (4.0.3)     
Requirement already satisfied: attrs==23.2.0 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 6)) (23.2.0)
Requirement already satisfied: better-proxy==1.2.0 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 7)) (1.2.0)      
Requirement already satisfied: colorama==0.4.6 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 8)) (0.4.6)
Requirement already satisfied: fake-useragent==1.5.1 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 9)) (1.5.1)    
Requirement already satisfied: frozenlist==1.4.1 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 10)) (1.4.1)       
Requirement already satisfied: greenlet==3.0.3 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 11)) (3.0.3)
Requirement already satisfied: idna==3.7 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 12)) (3.7)
Requirement already satisfied: loguru==0.7.2 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 13)) (0.7.2)
Requirement already satisfied: multidict==6.0.5 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 14)) (6.0.5)        
Requirement already satisfied: pyaes==1.6.1 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 15)) (1.6.1)
Requirement already satisfied: pydantic==2.8.2 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 16)) (2.8.2)
Requirement already satisfied: pydantic-settings==2.3.4 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 17)) (2.3.4)
Requirement already satisfied: pydantic_core==2.20.1 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 18)) (2.20.1)  
Requirement already satisfied: pyee==11.1.0 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 19)) (11.1.0)
Requirement already satisfied: Pyrogram==2.0.106 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 20)) (2.0.106)
Requirement already satisfied: PySocks==1.7.1 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 21)) (1.7.1)
Requirement already satisfied: python-dotenv==1.0.1 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 22)) (1.0.1)
Requirement already satisfied: TgCrypto==1.2.5 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 23)) (1.2.5)
Requirement already satisfied: typing_extensions==4.12.2 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 24)) (4.12.2)
Requirement already satisfied: win32-setctime==1.1.0 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 25)) (1.1.0)
Requirement already satisfied: yarl==1.9.4 in c:\lib\bots\hamsterkombatbot\venv\lib\site-packages (from -r requirements.txt (line 26)) (1.9.4)

(venv) c:\Lib\Bots\HamsterKombatBot>copy .env-example .env
Overwrite .env? (Yes/No/All): y
        1 file(s) copied.

(venv) c:\Lib\Bots\HamsterKombatBot>python main.py
Traceback (most recent call last):
  File "c:\Lib\Bots\HamsterKombatBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "c:\Lib\Bots\HamsterKombatBot\bot\utils\__init__.py", line 13, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments

(venv) c:\Lib\Bots\HamsterKombatBot>python main.py --action 1
Traceback (most recent call last):
  File "c:\Lib\Bots\HamsterKombatBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "c:\Lib\Bots\HamsterKombatBot\bot\utils\__init__.py", line 13, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments

(venv) c:\Lib\Bots\HamsterKombatBot>`

**Comment by shamhi** [comment]
Переустанови питон 3.11, либо удали path= в скобках

**Comment by UbeySofta** [comment]
> Переустанови питон 3.11, либо удали path= в скобках

Сам уже разобрался, но спасибо.

**Comment by DASTONBE** [comment]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\bot\core\tapper.py", line 8, in <module>
    from aiocfscrape import CloudflareScraper
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by DASTONBE** [comment]
> Переустанови питон 3.11, либо удали path= в скобках
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\bot\core\tapper.py", line 8, in <module>
    from aiocfscrape import CloudflareScraper
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Cexio-Tap-bot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3 что делать такой ошибка
