### ISSUE TITLE
Docker: libgobject-2.0.so.0: No such file or directory

### ISSUE THREAD

**Issue by fruitgum** [shamhi/HamsterKombatBot#2097]
Rebuilt with up-to-date repo
`docker buildx build . --tag hamster:latest`
`
docker run -v ./sessions:/app/sessions -v ./profiles.json:/app/profiles.json --env-file ./hamster.env --name hamsterEmma  -itd hamster:2.8 python3 main.py -a '2'
`
```
2024-07-29 11:41:33 | INFO     | 55 - Detected 1 sessions
...
Traceback (most recent call last):
  File "/app/bot/core/tapper.py", line 225, in run
    encoded_body = await get_mini_game_cipher(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bot/utils/scripts.py", line 108, in get_mini_game_cipher
    browser = await driver.chromium.launch(headless=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 14117, in launch
    await self._impl_obj.launch(
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_browser_type.py", line 94, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: BrowserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> /root/.cache/ms-playwright/chromium-1124/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disabl
e-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disabl
e-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsEle
ment,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-
prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search
-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data
-dir=/tmp/playwright_chromiumdev_profile-XXXXXXmTRQJg --remote-debugging-pipe --no-startup-window
<launched> pid=21
[pid=21][err] /root/.cache/ms-playwright/chromium-1124/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
[pid=21] <process did exit: exitCode=127, signal=null>
[pid=21] starting temporary directories cleanup
Call log:
<launching> /root/.cache/ms-playwright/chromium-1124/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disabl
e-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disabl
e-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsEle
ment,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-
prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search
-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data
-dir=/tmp/playwright_chromiumdev_profile-XXXXXXmTRQJg --remote-debugging-pipe --no-startup-window
  - <launched> pid=21
  - [pid=21][err] /root/.cache/ms-playwright/chromium-1124/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
  - [pid=21] <process did exit: exitCode=127, signal=null>
  - [pid=21] starting temporary directories cleanup


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/main.py", line 8, in main
    await process()
  File "/app/bot/utils/launcher.py", line 78, in process
    await run_tasks(tg_clients=tg_clients)
  File "/app/bot/utils/launcher.py", line 85, in run_tasks
    await asyncio.gather(*tasks)
  File "/app/bot/core/tapper.py", line 469, in run_tapper
    await Tapper(tg_client=tg_client).run(proxy=proxy)
  File "/app/bot/core/tapper.py", line 457, in run
    logger.error(f"{self.session_name} | Unknown error: {error}")
  File "/usr/local/lib/python3.11/site-packages/loguru/_logger.py", line 2056, in error
    __self._log("ERROR", False, __self._options, __message, args, kwargs)
  File "/usr/local/lib/python3.11/site-packages/loguru/_logger.py", line 2017, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/loguru/_colorizer.py", line 368, in prepare_simple_message
    parser.feed(string)
  File "/usr/local/lib/python3.11/site-packages/loguru/_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<launching>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7057ce866590>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7057ce76c0c0>, 2466.034231158)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7057ce76c3d0>, 2466.152607713)]', '[(<aiohttp.client_proto.ResponseHandler object a
t 0x7057ce76c590>, 2466.901712098)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7057ce7eb070>, 2467.190914779)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7057ce7eb4d0>, 2476.41582432)]']
connector: <aiohttp.connector.TCPConnector object at 0x7057ce866510>
```

**Comment by fruitgum** [comment]
Disregard this - I didn't set up envs properly
