### ISSUE TITLE
После обновления не хочет запускаться...

### ISSUE THREAD

**Issue by Hoochizoid** [shamhi/HamsterKombatBot#2159]
`C:\Python\HamsterKombatBot-main\venv\Scripts\python.exe path\HamsterKombatBot\main.py 
Traceback (most recent call last):
  File "path\HamsterKombatBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "path\HamsterKombatBot\bot\utils\__init__.py", line 4, in <module>
    from . import launcher
  File "path\HamsterKombatBot\bot\utils\launcher.py", line 7, in <module>
    from bot.config import settings
  File "path\HamsterKombatBot\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "path\HamsterKombatBot\bot\config\config.py", line 41, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Python\HamsterKombatBot-main\venv\Lib\site-packages\pydantic_settings\main.py", line 140, in __init__
    super().__init__(
  File "C:\Python\HamsterKombatBot-main\venv\Lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
apply_promo_game
  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden

Process finished with exit code 1`

**Comment by ilya125625262** [comment]
В файле (ENV) измени APPLY_PROMO_GAME= на APPLY_PROMO_CODES=

**Comment by Hoochizoid** [comment]
Спасибо. Заработало.
