### ISSUE TITLE
Получаю ошибку при запуске скрипта

### ISSUE THREAD

**Issue by lovipomidorku** [shamhi/HamsterKombatBot#2171]
`Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "C:\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\HamsterKombatBot-main\bot\utils\__init__.py", line 4, in <module>
    from . import launcher
  File "C:\HamsterKombatBot-main\bot\utils\launcher.py", line 7, in <module>
    from bot.config import settings
  File "C:\HamsterKombatBot-main\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\HamsterKombatBot-main\bot\config\config.py", line 43, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\HamsterKombatBot-main\venv\Lib\site-packages\pydantic_settings\main.py", line 140, in __init__
    super().__init__(
  File "C:\HamsterKombatBot-main\venv\Lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
API_ID
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
API_HASH
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
Для продолжения нажмите любую клавишу . . .`

Windows Server 2019, Python 3.11

**Comment by R2kip** [comment]
https://github.com/shamhi/HamsterKombatBot?tab=readme-ov-file#-получение-api-ключей

**Comment by lovipomidorku** [comment]
А я сначала указал API_HASH & API_ID а только потом запускал INSTALL.bat
