### ISSUE TITLE
Traceback: validation errors for Settings API_ID Field required. 

### ISSUE THREAD

**Issue by Arsiprog** [shamhi/HamsterKombatBot#218]
Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\Arsenprog\Desktop\HamsterKombatBot-2.1\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\Arsenprog\Desktop\HamsterKombatBot-2.1\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\Arsenprog\Desktop\HamsterKombatBot-2.1\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "C:\Users\Arsenprog\Desktop\HamsterKombatBot-2.1\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\Arsenprog\Desktop\HamsterKombatBot-2.1\bot\config\config.py", line 30, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Users\Arsenprog\Desktop\HamsterKombatBot-2.1\venv\Lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\Users\Arsenprog\Desktop\HamsterKombatBot-2.1\venv\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
API_ID
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
API_HASH
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
Для продолжения нажмите любую клавишу . . .

**Comment by doctormors** [comment]
Check the configuration file to see if it is filled in correctly

MIN_AVAILABLE_ENERGY=100
SLEEP_BY_MIN_ENERGY=[845,1600]

ADD_TAPS_ON_TURBO=2500

AUTO_UPGRADE=True
MAX_LEVEL=20

BALANCE_TO_SAVE=100000
UPGRADES_COUNT=20

APPLY_DAILY_ENERGY=False
APPLY_DAILY_TURBO=True

RANDOM_TAPS_COUNT=[23,381]
SLEEP_BETWEEN_TAP=[20,60]
USE_PROXY_FROM_FILE=False

**Comment by ButCheR-PRO** [comment]
Open README.md and configure .env:
```
API_ID=
API_HASH=
```

# Obtaining API Keys
1. Go to [my.telegram.org](https://my.telegram.org) and log in using your phone number.
2. Select **"API development tools"** and fill out the form to register a new application.
3. Note down the `API_ID` and `API_HASH` in `.env` file provided after registering your application.
