### ISSUE TITLE
[ERROR] Due to recent changes?

### ISSUE THREAD

**Issue by DineshValor** [shamhi/HamsterKombatBot#2266]
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/HamsterKombatBot/main.py", line 13, in <module>
    asyncio.run(main())
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/HamsterKombatBot/main.py", line 8, in main
    await process()
  File "/data/data/com.termux/files/home/HamsterKombatBot/bot/utils/launcher.py", line 80, in process
    await run_tasks(tg_clients=tg_clients)
  File "/data/data/com.termux/files/home/HamsterKombatBot/bot/utils/launcher.py", line 87, in run_tasks
    await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/HamsterKombatBot/bot/core/tapper.py", line 540, in run_tapper
    await Tapper(tg_client=tg_client).run(proxy=proxy)
  File "/data/data/com.termux/files/home/HamsterKombatBot/bot/core/tapper.py", line 52, in run
    headers = get_headers(name=self.tg_client.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/HamsterKombatBot/bot/utils/scripts.py", line 63, in get_headers
    profiles[name]['headers'] = headers
    ~~~~~~~~^^^^^^
KeyError: 'Hamster Valor'
(venv) ~/HamsterKombatBot $
```

What is new header line??
![Screenshot_20240827-155822](https://github.com/user-attachments/assets/59a3ab64-57d5-4f59-8d9a-4b758644f5f8)

**Comment by shamhi** [comment]
Did you use USE_RANDOM_USERAGENT option?

**Comment by DineshValor** [comment]
> Did you use USE_RANDOM_USERAGENT option?

Yep, enable

**Comment by shamhi** [comment]
Try updated

**Comment by DineshValor** [comment]
> Try updated

Yep error fixed
