### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by NotMRGH** [shamhi/HamsterKombatBot#2271]
I updated to the latest version today and I have a crash, if there was no problem before the update

```
Traceback (most recent call last):
  File "/root/HamsterKombatBot/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/HamsterKombatBot/main.py", line 8, in main
    await process()
  File "/root/HamsterKombatBot/bot/utils/launcher.py", line 80, in process
    await run_tasks(tg_clients=tg_clients)
  File "/root/HamsterKombatBot/bot/utils/launcher.py", line 87, in run_tasks
    await asyncio.gather(*tasks)
  File "/root/HamsterKombatBot/bot/core/tapper.py", line 540, in run_tapper
    await Tapper(tg_client=tg_client).run(proxy=proxy)
  File "/root/HamsterKombatBot/bot/core/tapper.py", line 65, in run
    if not proxy_conn.closed:
AttributeError: 'NoneType' object has no attribute 'closed'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd34c34c3d0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd345c8cbe0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd34513e410>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd34c3039a0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd345e76410>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd345e208b0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd34c303550>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd3458f7a30>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd3458f7670>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd345e17d60>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd34e4bdbd0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd3458f7040>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd34e65cf10>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd34557d330>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd34c302da0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd3458035e0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34e49cd60>, 866400.956525813)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345e2bd60>, 866401.214477825)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345e29300>, 866401.723959576)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345c0e620>, 866402.084687378)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34c093f40>, 866403.574094655)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd3456d0880>, 866403.717502765)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd34c34c490>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34581ba60>, 866402.97042348)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345770c40>, 866403.264422901)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34c183c40>, 866403.816716797)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345999a20>, 866404.195909296)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd345c8cc70>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345c7a740>, 866403.254351546)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345626920>, 866403.483933726)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd3454147c0>, 866404.063001616)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34543ca00>, 866404.417230983)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd34c3037c0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345624c40>, 866403.600811502)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd3456d2260>, 866403.863977125)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd3459191e0>, 866404.488726747)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd3454bac20>, 866404.861378763)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd3458f7850>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd3456248e0>, 866403.591113328)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd3456d1f60>, 866403.934194838)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34543c340>, 866404.612857041)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd3453597e0>, 866404.907817558)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd3458f76a0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345f5f460>, 866401.820659855)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345c78640>, 866402.126855181)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345a4c460>, 866402.623616674)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345918c40>, 866402.946832084)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345770f40>, 866404.538229678)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345359420>, 866404.670450337)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd345e17dc0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34e420fa0>, 866399.618476244)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34c296740>, 866399.880379106)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34c2972e0>, 866400.290723931)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34e486b00>, 866400.559023786)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345e2b1c0>, 866401.7611541)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd34e4e8bb0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd3456d3a60>, 866403.71792041)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345565180>, 866404.025014804)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34543cb20>, 866404.690989992)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd3458f6d40>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34e4234c0>, 866400.423765873)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34c297940>, 866400.664151895)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345f5ce80>, 866401.268719564)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345e2ab00>, 866401.539304441)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345d74520>, 866402.814130161)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345aeb280>, 866402.966443786)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd34e4bf670>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34c3825c0>, 866401.248075653)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345f5e260>, 866401.526953485)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345e2b7c0>, 866401.998837145)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd34c092f80>, 866402.293536551)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd345a4dd20>, 866403.856668909)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fd3456d3640>, 866403.994380451)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd34c302b60>
```

**Comment by shamhi** [comment]
[Fixed](https://github.com/shamhi/HamsterKombatBot/commit/016636e25e33a01e8d09a6f065114f8e24345a18)
