### ISSUE TITLE
Ошибка в боте

### ISSUE THREAD

**Issue by 9333003** [shamhi/HamsterKombatBot#2333]
Unknown error: 'rewardsByDays'

**Comment by ThePikachuuHD** [comment]
![image](https://github.com/user-attachments/assets/e3834ee9-069d-4979-8805-fd58635630be)
Есть решение? не фармит ключи и плитки после этой ошибки

**Comment by 9333003** [comment]
> ![image](https://private-user-images.githubusercontent.com/117750508/364543504-e3834ee9-069d-4979-8805-fd58635630be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0ODUwNzAsIm5iZiI6MTcyNTQ4NDc3MCwicGF0aCI6Ii8xMTc3NTA1MDgvMzY0NTQzNTA0LWUzODM0ZWU5LTA2OWQtNDk3OS04ODA1LWZkNTg2MzU2MzBiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQyMTE5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzBjZjg3YTBlYjgxYjlhYjVjZmYwY2U2ODY1Y2QyY2U4OTA2OGU0MDNhM2U2YWIwMDFlMjVlZTRiOTM0NDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l8MrbnYDOPTvdPkkWeIYbFx9ucl62m9hV66goXLtDn4) Есть решение? не фармит ключи и плитки после этой ошибки

APPLY_DAILY_REWARD=False
AUTO_COMPLETE_TASKS=False

Временное решение, чтобы убрать ошибку. Ждем фикс автора

**Comment by cmeept** [comment]
Отключи пока apply_daily_rewards мне помогло
> ![image](https://github.com/user-attachments/assets/e3834ee9-069d-4979-8805-fd58635630be)
> Есть решение? не фармит ключи и плитки после этой ошибки

**Comment by hardim26** [comment]
> Отключи пока apply_daily_rewards мне помогло
> 
> > ![image](https://private-user-images.githubusercontent.com/117750508/364543504-e3834ee9-069d-4979-8805-fd58635630be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0ODc1MTMsIm5iZiI6MTcyNTQ4NzIxMywicGF0aCI6Ii8xMTc3NTA1MDgvMzY0NTQzNTA0LWUzODM0ZWU5LTA2OWQtNDk3OS04ODA1LWZkNTg2MzU2MzBiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQyMjAwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmJlYTU2YmYwNTg5MGI3NTM5NmM1ZWUzZmNhNTY3ZWZiNDVmMzY2OTZhMmJlODFlMGI1NTA1ZTZlZWI0OTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cjhYu4PuRw7Wnc7pKtdTXFBTQCoTSUvIgm5giT9WQZ0)
> > Есть решение? не фармит ключи и плитки после этой ошибки

должно помочь.  APPLY_DAILY_REWARD=False в .env

**Comment by hardim26** [comment]
там ошибка еще rewardsCoin  - AUTO_COMPLETE_TASKS=False

**Comment by k0tone** [comment]
Разрабы перенесли информацию о суммах вознаграждения за Ежедневный стрик и за Ежедневные задания на другой URL.
было всё тут:
https://api.hamsterkombatgame.io/clicker/config
теперь часть информации тут:
https://api.hamsterkombatgame.io/clicker/config
и тут:
https://api.hamsterkombatgame.io/clicker/config/8Ef-Yt89VXi3KKlwZr1WjUP3uom91l7fnrzd-qPTHus

Эту часть можно достать из любого URL из его Response Headers - **config-version:**

Однако это вовсе и не нужно делать так как хватает и первого URL. Просто в коде нужно заккоментировать две строки:
Первая находится в блоке `if settings.APPLY_DAILY_REWARD:`
строка:
`rewards = daily_task['rewardsByDays']`

не забываем и про вывод лога, можете заменить на такое:
```
if is_completed:
    logger.success(f"{self.session_name} | Successfully get daily reward | "
                   f"Days: <lm>{days}</lm> | Reward coins: <lg>+{days - 1['rewardCoins']}</lg>")
```

Вторая в блоке `if settings.AUTO_COMPLETE_TASKS:`
строка:
`reward = task['rewardCoins']`

не забываем и про вывод лога, можете заменить на такое:
```
if is_completed:
    balance = int(profile_data.get('balanceCoins', 0))
    logger.success(f"{self.session_name} | "
                   f"Successfully completed <ly>{task_id}</ly> task | "
                   f"Balance: <lc>{balance}</lc> (<lg>+{100000}</lg>)")
```

**Comment by rufasu** [comment]
в `if settings.AUTO_COMPLETE_TASKS:` думаю надо еще изменить 
`if not is_completed and reward > 0:` 
на 
`if not is_completed:`

а в `if settings.APPLY_DAILY_REWARD:`
`f"Days: <lm>{days}</lm> | Reward coins: <lg>+{days - 1['rewardCoins']}</lg>")` 
ругается
`HamsterKombatBot-main\bot\core\tapper.py:228: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  f"Days: <lm>{days}</lm> | Reward coins: <lg>+{days - 1['rewardCoins']}</lg>")`

**Comment by 0x3x4by73** [comment]
> Unknown error: 'rewardsByDays'

[tapper.zip](https://github.com/user-attachments/files/16882628/tapper.zip)
Jus replace the tapper file with this and it's gonna work for you.

**Comment by AKTanara** [comment]
> `rewards = daily_task['rewardsByDays']`

Thanks
Can you please explain reason for this change of `min` to `max`?
![2024-09-05_132549](https://github.com/user-attachments/assets/819accc8-34de-4032-81bb-e8dd3fdb7a9b)
to
![2024-09-05_132601](https://github.com/user-attachments/assets/3153491f-624a-413d-9a0b-012354f906f0)

**Comment by socloseeee** [comment]
> > `rewards = daily_task['rewardsByDays']`
> 
> 
> 
> Thanks
> 
> Can you please explain reason for this change of `min` to `max`?
> 
> ![2024-09-05_132549](https://github.com/user-attachments/assets/819accc8-34de-4032-81bb-e8dd3fdb7a9b)
> 
> to
> 
> ![2024-09-05_132601](https://github.com/user-attachments/assets/3153491f-624a-413d-9a0b-012354f906f0)
> 
> 

It's just that he initially made a mistake, then corrected it.

**Comment by AKTanara** [comment]
> > > `rewards = daily_task['rewardsByDays']`
> > 
> > 
> > Thanks
> > Can you please explain reason for this change of `min` to `max`?
> > ![2024-09-05_132549](https://private-user-images.githubusercontent.com/20730424/364722864-819accc8-34de-4032-81bb-e8dd3fdb7a9b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzExMDcsIm5iZiI6MTcyNTUzMDgwNywicGF0aCI6Ii8yMDczMDQyNC8zNjQ3MjI4NjQtODE5YWNjYzgtMzRkZS00MDMyLTgxYmItZThkZDNmZGI3YTliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEwMDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYzcwMjMwMjQ0MTVkNjBkMDM1ZTY2NjM1YzRjMDk4MmM5OGYzMDc3ZDU1ZjI1MWI1ZTcwMzY0NzgwYjU3YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.13l5vho9bG-vNXJIFjSD8nsNlqT8Sx8C2yE1RGEGQZg)
> > to
> > ![2024-09-05_132601](https://private-user-images.githubusercontent.com/20730424/364722923-3153491f-624a-413d-9a0b-012354f906f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzExMDcsIm5iZiI6MTcyNTUzMDgwNywicGF0aCI6Ii8yMDczMDQyNC8zNjQ3MjI5MjMtMzE1MzQ5MWYtNjI0YS00MTNkLTlhMGItMDEyMzU0ZjkwNmYwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEwMDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2Zjg1MmRiZjRmZjdmOTg4ZWZlNjYwZGI0NGRlYmNjYTdmNGZlYjk4YjNmZDhjMjViMzc4ZjU4Y2Q1ZThkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bn3MrMiuUTFk6qnG2HdRCkV5DBsAk5EdRB51vT-NZYk)
> 
> It's just that he initially made a mistake, then corrected it.

And here replacing `{reward}` with `{100000}` means that code should be corrected for following days?
![image](https://github.com/user-attachments/assets/dcecc677-9fca-4a70-b9b2-a3d6e1e2d66b)

**Comment by AKTanara** [comment]
> > Unknown error: 'rewardsByDays'
> 
> [tapper.zip](https://github.com/user-attachments/files/16882628/tapper.zip) Jus replace the tapper file with this and it's gonna work for you.

I already have claimed daily reward and yet I get this message each time I run the bot:
`2024-09-05 14:15:01 | SUCCESS  | 218 - MySession | Successfully get daily reward | Days: 1 | Reward coins: +0`

**Comment by Ruslan779555** [comment]
> > Unknown error: 'rewardsByDays'
> 
> [tapper.zip](https://github.com/user-attachments/files/16882628/tapper.zip) Jus replace the tapper file with this and it's gonna work for you.

Traceback (most recent call last):
  File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\utils\__init__.py", line 4, in <module>
    from . import launcher
  File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\utils\launcher.py", line 11, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\core\tapper.py", line 19, in <module>
    from bot.api.clicker import (
ImportError: cannot import name 'get_version_config' from 'bot.api.clicker' (C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\api\clicker.py)


After replacing the file I get an error

**Comment by AKTanara** [comment]
> ![photo_2024-09-05_15-16-36](https://private-user-images.githubusercontent.com/169262694/364771614-d970655a-46c5-42c0-8cdb-f2c1e8a0ec2c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDk3MzEsIm5iZiI6MTcyNTU0OTQzMSwicGF0aCI6Ii8xNjkyNjI2OTQvMzY0NzcxNjE0LWQ5NzA2NTVhLTQ2YzUtNDJjMC04Y2RiLWYyYzFlOGEwZWMyYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNTE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzkwNGE2ZTVjYWYzZGMzMTNjMjFkYzYxNmQ1NWNmNzNjOGEwODg5MGIyMjViMGJiOTM2YmNhNzE4MWMyNGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mYwJ8janri43jGbnB5zrose5VsZfzbrqD8ds_IqEEcc)
> 
> > > Unknown error: 'rewardsByDays'
> > 
> > 
> > [tapper.zip](https://github.com/user-attachments/files/16882628/tapper.zip) Jus replace the tapper file with this and it's gonna work for you.
> 
> Traceback (most recent call last): File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\main.py", line 4, in from bot.utils.launcher import process File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\utils__init__.py", line 4, in from . import launcher File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\utils\launcher.py", line 11, in from bot.core.tapper import run_tapper File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\core\tapper.py", line 19, in from bot.api.clicker import ( ImportError: cannot import name 'get_version_config' from 'bot.api.clicker' (C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\api\clicker.py)
> 
> After replacing the file I get an error
This works for me flawlessly:
[tapper.zip](https://github.com/user-attachments/files/16896588/tapper.zip)

**Comment by AKTanara** [comment]
> ![photo_2024-09-05_15-16-36](https://private-user-images.githubusercontent.com/169262694/364771614-d970655a-46c5-42c0-8cdb-f2c1e8a0ec2c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDk4ODgsIm5iZiI6MTcyNTU0OTU4OCwicGF0aCI6Ii8xNjkyNjI2OTQvMzY0NzcxNjE0LWQ5NzA2NTVhLTQ2YzUtNDJjMC04Y2RiLWYyYzFlOGEwZWMyYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNTE5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmJmNGE0NzlhNDlkN2JmYTFmZjQyYzU1ODI5MGExY2Q2Yjk4ODNiZGZhMWRjNGQwMTc4Nzg0NTI5NDEyMTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q3WUOJDEcKHoocfeauvEjXUVw-zamw5co3aT2LbEH2A)
> 
> > > Unknown error: 'rewardsByDays'
> > 
> > 
> > [tapper.zip](https://github.com/user-attachments/files/16882628/tapper.zip) Jus replace the tapper file with this and it's gonna work for you.
> 
> Traceback (most recent call last): File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\main.py", line 4, in from bot.utils.launcher import process File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\utils__init__.py", line 4, in from . import launcher File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\utils\launcher.py", line 11, in from bot.core.tapper import run_tapper File "C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\core\tapper.py", line 19, in from bot.api.clicker import ( ImportError: cannot import name 'get_version_config' from 'bot.api.clicker' (C:\Users\tegra\OneDrive\Desktop\Тапалка\Руслан\HamsterKombatBot-main\bot\api\clicker.py)
> 
> After replacing the file I get an error

This works for me flawlessly:
[tapper.zip](https://github.com/user-attachments/files/16896588/tapper.zip)
