### ISSUE TITLE
Traceback: from config import settings APII_HASH: SyntaxError: invalid decimal literal

### ISSUE THREAD

**Issue by crispan2** [shamhi/HamsterKombatBot#234]
Traceback (most recent call last):
  File "c:\Users\valdo\Desktop\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "c:\Users\valdo\Desktop\HamsterKombatBot-main\bot\utils\__init__.py", line 2, in <module> 
    from . import launcher
  File "c:\Users\valdo\Desktop\HamsterKombatBot-main\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "c:\Users\valdo\Desktop\HamsterKombatBot-main\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "c:\Users\valdo\Desktop\HamsterKombatBot-main\bot\config\config.py", line 8
    API_HASH: 9da4f**********b212****30
              ^
SyntaxError: invalid decimal literal

звездочки - чтобы не палить хэш

**Comment by ButCheR-PRO** [comment]
Оно говорит, что в конфиге .env  API_HASH должен быть в строковом формате. 
Перепроверь свой .env, там не должно быть пробелов. А ещё, какая у тебя версия Python?

**Comment by cgcore** [comment]
hi, i have same problem
(venv) C:\YesCoin-Clicker>python main.py
Traceback (most recent call last):
  File "C:\YesCoin-Clicker\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\YesCoin-Clicker\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\YesCoin-Clicker\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "C:\YesCoin-Clicker\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\YesCoin-Clicker\bot\config\config.py", line 29, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\YesCoin-Clicker\venv\Lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\YesCoin-Clicker\venv\Lib\site-packages\pydantic\main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
SLEEP_BY_MIN_ENERGY
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='[1800,2500]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/int_parsing

**Comment by cgcore** [comment]
> Оно говорит, что в конфиге .env API_HASH должен быть в строковом формате. Перепроверь свой .env, а именно строку `API_HASH=` там не должно быть пробелов, точек и кавычек, звёздочек или спецсимволов. А ещё, какая у тебя версия Python? И в какой кодировке сохранён файл .env? Файл .env должен выглядеть примерно так:
> 
> ```
> API_ID=25019594
> API_HASH=9da4fffd676a4188606fa01d4eb21230
> ```

**Comment by cgcore** [comment]
> API_ID=25019594
> API_HASH=9da4fffd676a4188606fa01d4eb21230

when  i want take this tow api from telegram website, after clicking create bottom. show error message with no text

**Comment by cgcore** [comment]
where i can find hamsterbat script
