### ISSUE TITLE
что делать

### ISSUE THREAD

**Issue by bratosd3** [shamhi/HamsterKombatBot#2374]
Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\Professional\Desktop\dark\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\Professional\Desktop\dark\HamsterKombatBot-main\bot\utils\__init__.py", line 1, in <module>
    from .logger import logger
  File "C:\Users\Professional\Desktop\dark\HamsterKombatBot-main\bot\utils\logger.py", line 2, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
Для продолжения нажмите любую клавишу . . .

**Comment by WeendVidente777** [comment]
pip install loguru или как то так. Не помню как в питоне модули устанавливать. 
Модуля кароч нету, установи.

**Comment by bratosd3** [comment]
спасибо

**Comment by bratosd3** [comment]
тоже самое не помогло

**Comment by WeendVidente777** [comment]
> ModuleNotFoundError: No module named 'loguru'

тоже ModuleNotFoundError: No module named 'loguru'
Или какое то другое название модуля? Если другое - то и его установи, и так пока не заведется. 
А если то же самое, то я хз.

**Comment by afillimonov** [comment]
> Activating virtual environment...
> Starting the bot...
> Traceback (most recent call last):
>   File "C:\Users\Professional\Desktop\dark\HamsterKombatBot-main\main.py", line 4, in <module>
>     from bot.utils.launcher import process
>   File "C:\Users\Professional\Desktop\dark\HamsterKombatBot-main\bot\utils\__init__.py", line 1, in <module>
>     from .logger import logger
>   File "C:\Users\Professional\Desktop\dark\HamsterKombatBot-main\bot\utils\logger.py", line 2, in <module>
>     from loguru import logger
> ModuleNotFoundError: No module named 'loguru'
> Для продолжения нажмите любую клавишу . . .

Нужен питон 3.11 версии

**Comment by hardim26** [comment]
> тоже самое не помогло

удали папку venv и повторно сделай install.bat
