### ISSUE TITLE
Ошибка: TypeError: unsupported operand type(s) for |: '_LiteralGenericAlias' and 'NoneType'

### ISSUE THREAD

**Issue by 6322n** [shamhi/HamsterKombatBot#2388]
При запуске бота вылазит следующая ошибка:
Traceback (most recent call last):
  File "/root/HamsterKombatBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/HamsterKombatBot/bot/utils/__init__.py", line 3, in <module>
    from . import tg_web_data
  File "/root/HamsterKombatBot/bot/utils/tg_web_data.py", line 16, in <module>
    from bot.utils.proxy import get_proxy_dict
  File "/root/HamsterKombatBot/bot/utils/proxy.py", line 2, in <module>
    from better_proxy import Proxy
  File "/root/HamsterKombatBot/venv/lib/python3.9/site-packages/better_proxy/__init__.py", line 1, in <module>
    from .proxy import Proxy, parse_proxy_str
  File "/root/HamsterKombatBot/venv/lib/python3.9/site-packages/better_proxy/proxy.py", line 16, in <module>
    class ParsedProxy(TypedDict):
  File "/root/HamsterKombatBot/venv/lib/python3.9/site-packages/better_proxy/proxy.py", line 19, in ParsedProxy
    protocol: Protocol | None
TypeError: unsupported operand type(s) for |: '_LiteralGenericAlias' and 'NoneType'

Что это может быть?

**Comment by Petr6666** [comment]
Проверь для начала версию python, и актуальное время на своём компьютере, в целом этого уже достаточно для решения твоей проблемы, я использую python 3.11.9 все работает без проблем
