### ISSUE TITLE
Unable to run the bot. (ModuleNotFoundError: No module named 'pydantic_core._pydantic_core')

### ISSUE THREAD

**Issue by tertaco** [shamhi/HamsterKombatBot#242]
Using Python 3.11.9 from Microsoft Store, getting error:

```
Starting the bot...
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "C:\Users\User\Desktop\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\User\Desktop\HamsterKombatBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\User\Desktop\HamsterKombatBot-main\bot\utils\launcher.py", line 8, in <module>
    from better_proxy import Proxy
  File "C:\Users\User\Desktop\HamsterKombatBot-main\venv\Lib\site-packages\better_proxy\__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "C:\Users\User\Desktop\HamsterKombatBot-main\venv\Lib\site-packages\better_proxy\proxy.py", line 5, in <module>
    from pydantic import BaseModel
  File "C:\Users\User\Desktop\HamsterKombatBot-main\venv\Lib\site-packages\pydantic\__init__.py", line 383, in __getattr__
    module = import_module(module_name, package=package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\HamsterKombatBot-main\venv\Lib\site-packages\pydantic\main.py", line 12, in <module>
    import pydantic_core
  File "C:\Users\User\Desktop\HamsterKombatBot-main\venv\Lib\site-packages\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'
Для продолжения нажмите любую клавишу . . .
```

**Comment by xqShayze** [comment]
Download the latest version of Python from the official website, first removing 3.11.9, and before using it, run the install.bat file. It is also worth reinstalling the bot from the old version, if you had it, to the latest released update.

**Comment by tertaco** [comment]
> Download the latest version of Python from the official website, first removing 3.11.9, and before using it, run the install.bat file. It is also worth reinstalling the bot from the old version, if you had it, to the latest released update.

I used all versions of Python starting from 3.10; none of them worked.I always run the INSTALL.BAT file and always check if there're any updates on this bot.

**Comment by xqShayze** [comment]
When you run INSTALL.BAT, do you have a complete installation of libraries without any errors?

**Comment by tertaco** [comment]
> When you run INSTALL.BAT, do you have a complete installation of libraries without any errors?

Yes

**Comment by stalker-run** [comment]
Read what it says after installing all the files for python, it says fill in the file .env
Fill in
API_ID=
API_HASH=

**Comment by tertaco** [comment]
> Read what it says after installing all the files for python, it says fill in the file .env
> 
> Fill in
> 
> API_ID=
> 
> API_HASH=
> 
> 
> 
> Заполни файл .env, этим вроде фиксил

Да я уже пофиксил, там где два значения надо было указать я думал что [] не надо добавлять :^)

**Comment by ButCheR-PRO** [comment]
Дубликат https://github.com/shamhi/HamsterKombatBot/issues/123
