### ISSUE TITLE
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

### ISSUE THREAD

**Issue by xqShayze** [shamhi/HamsterKombatBot#250]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\App\Python\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "D:\App\Python\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

**Comment by xqShayze** [comment]
Всё пофиксил, 1 из сессий слетела, пришлось пересоздать, и всё ок.
