### ISSUE TITLE
What is this thing can anyone explain ? 

### ISSUE THREAD

**Issue by ReZMoH85** [shamhi/HamsterKombatBot#279]
BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized.
BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized.

**Comment by ReZMoH85** [comment]
> BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized. BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized.

BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized.
Traceback (most recent call last):
  File "E:\Hamster\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\ReZNuM\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ReZNuM\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ReZNuM\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Hamster\main.py", line 8, in main
    await process()
  File "E:\Hamster\bot\utils\launcher.py", line 92, in process
    await register_sessions()
  File "E:\Hamster\bot\core\registrator.py", line 26, in register_sessions
    async with session:
  File "E:\Hamster\venv\Lib\site-packages\pyrogram\client.py", line 311, in __aenter__
    return await self.start()
           ^^^^^^^^^^^^^^^^^^
  File "E:\Hamster\venv\Lib\site-packages\pyrogram\methods\utilities\start.py", line 62, in start
    await self.authorize()
  File "E:\Hamster\venv\Lib\site-packages\pyrogram\client.py", line 359, in authorize
    sent_code = await self.send_code(self.phone_number)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Hamster\venv\Lib\site-packages\pyrogram\methods\auth\send_code.py", line 79, in send_code
    return types.SentCode._parse(r)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Hamster\venv\Lib\site-packages\pyrogram\types\authorization\sent_code.py", line 58, in _parse
    type=enums.SentCodeType(type(sent_code.type)),
                                 ^^^^^^^^^^^^^^
AttributeError: 'BadMsgNotification' object has no attribute 'type'

**Comment by XPacL** [comment]
Написан ответ на твой вопрос в первой же строчке ошибки... Ты хоть потрудись почитать прежде чем задавать вопрос

**Comment by ReZMoH85** [comment]
> The answer to your question is written in the very first line of the error... At least bother to read before asking a question

I read it but i dunno how to fix it

**Comment by XPacL** [comment]
Ну там же написано, что у тебя время не синхронизировано. Куда ещё доходчивее можно объяснить? Сделай это, установи правильное время на своём компьютере.
