### ISSUE TITLE
How can I fix the error?

### ISSUE THREAD

**Issue by MikhailKamado** [shamhi/HamsterKombatBot#319]
How can I fix the error?
```
Activating virtual environment...
Starting the bot...
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "C:\Users\mikha\OneDrive\Рабочий стол\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\mikha\OneDrive\Рабочий стол\HamsterKombatBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\mikha\OneDrive\Рабочий стол\HamsterKombatBot-main\bot\utils\launcher.py", line 8, in <module>
    from better_proxy import Proxy
  File "C:\Users\mikha\OneDrive\Рабочий стол\HamsterKombatBot-main\venv\Lib\site-packages\better_proxy\__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "C:\Users\mikha\OneDrive\Рабочий стол\HamsterKombatBot-main\venv\Lib\site-packages\better_proxy\proxy.py", line 5, in <module>
    from pydantic import BaseModel
  File "C:\Users\mikha\OneDrive\Рабочий стол\HamsterKombatBot-main\venv\Lib\site-packages\pydantic\__init__.py", line 383, in __getattr__
    module = import_module(module_name, package=package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mikha\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mikha\OneDrive\Рабочий стол\HamsterKombatBot-main\venv\Lib\site-packages\pydantic\main.py", line 12, in <module>
    import pydantic_core
  File "C:\Users\mikha\OneDrive\Рабочий стол\HamsterKombatBot-main\venv\Lib\site-packages\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'
```

**Comment by yoyoallf** [comment]
cmd - напиши pip install pydantic_core

**Comment by Jackricher1990** [comment]
win10sdk should be installed

**Comment by yoyoallf** [comment]
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools"

Нужно установить)

**Comment by MikhailKamado** [comment]
win10sdk установил не помогло

**Comment by MikhailKamado** [comment]
> > ошибка: требуется Microsoft Visual C ++ 14.0 или более поздней версии. Получите ее с помощью "Microsoft C ++ Build Tools"
> 
> Нужно установить)

Я пытался установить, написало что данная или новее версия уже стоит на компьютере
