### ISSUE TITLE
Eror no run HamsterKombatBot-main>

### ISSUE THREAD

**Issue by nvquangil** [shamhi/HamsterKombatBot#373]
(venv) D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main>python main.py
Traceback (most recent call last):
  File "D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main\bot\utils\__init__.py", line 8, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments

run statt.bat
Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main\bot\utils\__init__.py", line 8, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments
Press any key to continue . . .

Thanks

**Comment by ButCheR-PRO** [comment]
Install and configure all correctly:
1. https://github.com/shamhi/HamsterKombatBot/issues/290#issuecomment-2162692634
