### ISSUE TITLE
после нового обновления

### ISSUE THREAD

**Issue by ayumil0l** [shamhi/HamsterKombatBot#59]
Traceback (most recent call last):
  File "D:\HamsterKombatBot-main\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\aevav\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\aevav\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\HamsterKombatBot-main\main.py", line 8, in main
    await process()
  File "D:\HamsterKombatBot-main\bot\utils\launcher.py", line 93, in process
    await run_tasks(tg_clients=tg_clients)
  File "D:\HamsterKombatBot-main\bot\utils\launcher.py", line 102, in run_tasks
    await asyncio.gather(*tasks)
  File "D:\HamsterKombatBot-main\bot\core\tapper.py", line 419, in run_tapper
    await Tapper(tg_client=tg_client).run(proxy=proxy)
  File "D:\HamsterKombatBot-main\bot\core\tapper.py", line 265, in run
    tg_web_data = await self.get_tg_web_data(proxy=proxy)
  File "D:\HamsterKombatBot-main\bot\core\tapper.py", line 41, in get_tg_web_data
    tg_web_data = get_auth_key(self.tg_client.name)
  File "D:\HamsterKombatBot-main\bot\utils\scripts.py", line 7, in get_auth_key
    auth_keys = json.load(file)
  File "C:\Users\aevav\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\aevav\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aevav\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aevav\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 22 (char 23)

до этого было все норм (помимо 422 ерроров конечно)

**Comment by darhanger** [comment]
У меня 
![image](https://github.com/shamhi/HamsterKombatBot/assets/22445395/22fd3c0e-7250-42a0-a677-44a8fc5adf22)


Но скорее всего сервак прилоги отвалился.

**Comment by TkikT1** [comment]
![Screenshot_1](https://github.com/shamhi/HamsterKombatBot/assets/141658028/5ca83d13-b987-4ffc-a389-a2d2a0dcc0a3)
тоже так

**Comment by shamhi** [comment]
покажи что в auth_keys.json

**Comment by ayumil0l** [comment]
> покажи что в auth_keys.json

была просто скобочка
удалил файл, снова запустил, теперь это
![image](https://github.com/shamhi/HamsterKombatBot/assets/58660416/81c55ab9-fbc5-4bad-826b-baebfbd47ce9)

**Comment by ButCheR-PRO** [comment]
Советую установить [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Затем синхронизировать на компьютере системное время.
Скачать последнюю версию бота
Потом запустить INSTALL.bat. 
Затем настроить конфиг .env согласно документации в README.md
После этого создать сессию через START.bat выбрав пункт 1. 
И только потом запускать настроенный кликер через START.bat выбрав пункт 2.
