### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by faizahmaddae** [shamhi/HamsterKombatBot#61]
Select an action:

    1. Create session
    2. Run clicker

> 2
Traceback (most recent call last):
  File "/home/faiz/HamsterKombatBot/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/faiz/HamsterKombatBot/main.py", line 8, in main
    await process()
  File "/home/faiz/HamsterKombatBot/bot/utils/launcher.py", line 93, in process
    await run_tasks(tg_clients=tg_clients)
  File "/home/faiz/HamsterKombatBot/bot/utils/launcher.py", line 102, in run_tasks
    await asyncio.gather(*tasks)
  File "/home/faiz/HamsterKombatBot/bot/core/tapper.py", line 422, in run_tapper
    await Tapper(tg_client=tg_client).run(proxy=proxy)
  File "/home/faiz/HamsterKombatBot/bot/core/tapper.py", line 265, in run
    tg_web_data = await self.get_tg_web_data(proxy=proxy)
  File "/home/faiz/HamsterKombatBot/bot/core/tapper.py", line 41, in get_tg_web_data
    tg_web_data = get_auth_key(self.tg_client.name)
  File "/home/faiz/HamsterKombatBot/bot/utils/scripts.py", line 7, in get_auth_key
    auth_keys = json.load(file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 3 column 2 (char 312)
(venv) faiz@faizserver:~/HamsterKombatBot$ 

<img width="679" alt="Screenshot 2024-05-23 at 8 34 41 AM" src="https://github.com/shamhi/HamsterKombatBot/assets/8683191/5e57b8b4-9f18-414f-ba7f-120fa3518420">

**Comment by shamhi** [comment]
fixed
update repo, delete auth_keys.file, and run again
